throw используется частью кода, обнаружившего проблему. Передаёт исключение.

    5.6.1 Оператор throw

if (item1.isbn() != item2.isbn())
    throw runtime_error("Data must refer to same ISBN");
cout << item1 + item2 << endl; // isbn совпадают

Если было передано исключение, тогда работа текущей функции завершается.
Передается кправление обработчику, способному справиться с этой ошибкой.
runtime_error является одним из типов исклчений, определённых в stdexcept.

    5.6.2 Блок try
Синтаксис:
try {
    operators
} catch (except) {
    process operators
} catch (except) {
    process operators
}

while (cin >> it1 >> it2){
    try {
        // код, складывающий элементы класса
        // если исключение - передать ошибку runtime_error
    } catch (runtime_error err) { // передает ошибку сюда
        cout << err.what() << "try again?\n";
        char c;
        cin >> c;
        if (!cin || c == 'n')
            break;
    }
}

Тип runtime_error - const char*.
В сложных программах существует несколько уровней try.
Если не было найдено блоков-обработчиков - управление передается в terminate().
terminate() обычно завершает программу.
Написание устойчивого к исключениям кода - сложная задача.

    5.6.3 Стандартные исключения
В заголовке exception определён общий класс exception.
Сообщает что исключение было, без доп. информации.
stdexcept - несколько универсальных классов исключения.
В new - класс исключения bad_alloc.
type_info - класс исключения bad_cast.

Классы из stdexcept:
exception - наиболее общий вид проблемы
runtime_error - проблемы обнаружена только во время выполнения
range_error - ошибка времени выыполнения - результат превосходит диапазон значений
overflow_error - переполнение регистра при вычислении
underflow_error - недополнение решистра при вычислении
logic_error - логическая ошибка
domain_error - аргумент, для которого не существует результата
invalid_argument - аргумент, для которого не существует результата
lenght_error - попытка создать обьект больше допустимого для данного типа
out_of_range - значение вне допустимого диапазона

В классах исключений только 1 функция - what().
Возвращает строку в стиле С, содержащую текст данного исключения.